---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: centos-7.3
    run_list:
    - recipe[yum]
  - name: debian-8.7
    run_list:
    - recipe[apt]
  - name: fedora-25
    run_list:
    - recipe[yum]
  - name: ubuntu-16.04
    run_list:
    - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[postfix]
    - recipe[rkhunter]
  attributes: {
    postfix: {
      main: {
        myhostname: 'example.com'
      }
    },
    rkhunter: {
      report_email: 'you@example.com',
      db_update_email: 'true',
      cron_db_update: 'true',
      cron_daily_run: 'true'
    }
  }
