name 'rkhunter'
maintainer 'gregpalmier'
maintainer_email 'gregpalmier@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures rkhunter'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.2.5'
depends 'apt'
depends 'postfix'
depends 'yum'
