default['rkhunter']['cron_daily_run']		= ""
default['rkhunter']['cron_db_update']		= ""
default['rkhunter']['db_update_email']		= "false"
default['rkhunter']['report_email']		= "root"
default['rkhunter']['apt_autogen']		= "false"
default['rkhunter']['nice']			= "0"
default['rkhunter']['run_check_on_battery']	= "false"
